# NFSv3 Programs
NFSPROC3_NULL = 0
NFSPROC3_GETATTR = 1
NFSPROC3_SETATTR = 2
NFSPROC3_LOOKUP = 3

NFS_PROC_CODES = {
    'NULL': 0, 'GETATTR': 1, 'LOOKUP': 3, 'ACCESS': 4, 'READDIRPLUS': 17, 'FSSTAT': 18,
}